baseURL = "https://elated-mirzakhani-1ac588.netlify.app/"
languageCode = "en-us"
title = "Test site for Distill"
theme = "distillpub"
[menu]

  [[menu.main]]
  identifier = "about"
  name = "About Hugo"
  title = "about"
  url = "/about"
  weight = -10

[params]

  color = "#6EA9B7"

